### ISSUE TITLE
⬆ Upgrade Alpine Image 3.15 -> 3.16

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/network-access-control-server#139]
### User Story

As a… Cloud Ops Admin
I expect the build image to be up to date

### Value / Purpose

ETC

### Definition of Done

- [ ] tests passing successfully
- [ ] PR created and merged, approved to production

**Comment by mitchdawson1982** [comment]
The original Alpine upgrade led to a number of additional changes that were required to support it. Python3.10 was now included with Alpine 3.16 and there was an issue with Freeradius  3.2 RLM_Python module building under this version and Freeradius 3.2.1 was released to address this as well as a number of other ones. Also the version of Openssl had to be downgraded to 1.1.1-s-r0 from 1.1.1-s-r1 due to a lack of support in Alpine. Packages can be found [here ](https://pkgs.alpinelinux.org/packages?name=openssl&branch=v3.16&repo=&arch=x86_64&maintainer=). 

There was a spike in rejected requests when the upgrade was pushed into live and was subsequently backed out.
Initial investigations of the cloudwatch logs indicate issues with the values contained in the payload that is passed to the policy engine.

Log Entries - 

fits-4443_-_probation_-_grimsby POLICY ENGINE: Request Attributes - {'EAP-Message': '0x02d400060d00', 'FreeRADIUS-Proxied-To': '127.0.0.1', 'User-Name': 'host/EUD021159.dom1.infra.int', 'State': '0xacc483cda8108e30d0ab8c4b02a9ebc2', 'Called-Station-Id': 'D4-DC-09-05-C8-12:MoJWifi', 'NAS-Port-Type': 'Wireless-802.11', 'Service-Type': 'Framed-User', 'Calling-Station-Id': '70-9c-d1-1c-a3-72', 'Connect-Info': 'CONNECT 0Mbps 802.11b', 'Acct-Session-Id': 'CCAA4A6286920541', 'Acct-Multi-Session-Id': '808CAFFDED78771D', 'WLAN-Pairwise-Cipher': '1027076', 'WLAN-Group-Cipher': '1027076', 'WLAN-AKM-Suite': '1027073', 'Framed-MTU': '1200', 'NAS-IP-Address': '10.149.193.11', 'Event-Timestamp': 'Jan 17 2023 11:33:21 UTC', 'EAP-Type': 'TLS', 'TLS-Client-Cert-Serial': '3b001200f652b09b4804d9bb040001001200f6', 'TLS-Client-Cert-Expiration': '240103083626Z', 'TLS-Client-Cert-Valid-Since': '230103083626Z', 'TLS-Client-Cert-Subject': '/CN=EUD021159.dom1.infra.int', 'TLS-Client-Cert-Issuer': '/DC=internal/DC=lexlive/CN=EUCRSAENTCA001', 'TLS-Client-Cert-Common-Name': 'EUD021159.dom1.infra.int', 'TLS-Client-Cert-X509v3-Subject-Key-Identifier': '7B:AD:9B:3E:FF:4C:8D:05:15:A0:DD:58:66:49:D0:F2:7C:64:AA:48', 'TLS-Client-Cert-X509v3-Basic-Constraints': 'CA:TRUE, pathlen:1', 'TLS-Client-Cert-X509v3-Authority-Key-Identifier': 'keyid:67:95:58:A4:EB:DC:DB:CC:C3:12:C9:86:36:3F:B4:FE:01:5B:C1:78
', 'TLS-Client-Cert-Subject-Alt-Name-Upn': 'EUD021159$@dom1.infra.int', 'TLS-Client-Cert-Subject-Alt-Name-Dns': 'EUD021159.dom1.infra.int', 'TLS-Client-Cert-X509v3-Extended-Key-Usage': 'TLS Web Client Authentication', 'TLS-Client-Cert-X509v3-Extended-Key-Usage-OID': '1.3.6.1.5.5.7.3.2', 'Client-Shortname': 'fits-4443_-_probation_-_grimsby'}

fits-4443_-_probation_-_grimsby POLICY ENGINE: Policy Response - (('Post-Auth-Type', 'Reject'),)

post_auth - 'reply:Post-Auth-Type' = 'Reject'

do_python_single:675, post_auth - RLM_MODULE_FAIL

 [python3] = fail
